[build]
  command = "yarn install && yarn build:preview"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.20.2"
  YARN_VERSION = "3.2.1"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

# Force browser to not use cached versions
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "no-cache"
