[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider yarn install && NODE_OPTIONS=--openssl-legacy-provider yarn build:preview"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.10.0"
  YARN_VERSION = "3.2.1"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_PUBLISHABLE_API_KEY"

# Force browser to not use cached versions
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "no-cache"
